try-catch

try {

} catch (e) {
  // try 에서 에러가 발생하면 실행할 구문
}
===> 기본 구조

예) 
try {
  x();
} catch (e) {              -----> e  는 에러객체
  console.log('에러 발생'); -----> x 가 존재하지 않기 떄문에 바로 '에러 발생'이 나온다.
}

try {

} catch (e) {
  // try 에서 에러가 발생하면 실행할 구문.
} finally {
  // 어떠한 상황에서도 실행된다.
}
===> try - catch(에러가 있으면 실행) - finally(언제나 실행)



